Added the get all requests endpoint
bliu23/conveni-friends pull request #19
Opened 2017-11-15 07:20 UTC by parkandrew

2017-11-15 07:40 UTC, bliu23 commented on server/server.js
> +                + `WHERE accepted is NULL`;
nit: plus sign should go on the previous line for better readability (personal preference)

2017-11-15 08:04 UTC, parkandrew commented
some weird git changes means this PR looks super weird.......

i think its trying to sync my fork with the upstream. lmk if you have any suggestions how to fix

2017-11-15 20:34 UTC, mmxiong requested changes

2017-11-15 20:34 UTC, mmxiong commented on server/server.js
> +// HTTP body parser
These changes were part of my PR, do you know why they are they showing up now?

2017-11-15 20:34 UTC, mmxiong commented on server/server.js
> +                  `WHERE accepted is NULL`;
Why do we want accepted to be null? Is it because this route should only be hit for the "show all nearby unaccepted requests" screen? And if we need requests that are accepted/confirmed/completed, they should be associated with a specific user, and we'll use the get requests for users route?

2017-11-15 20:34 UTC, mmxiong commented on server/server.js
> +// http://localhost:3000/v1/requests/all?userId="test"&location="testLocation"
Location is now a latitude/longitude. We should return only requests that are reasonably close to the coordinates.

2017-11-15 20:40 UTC, bliu23 commented on server/server.js
> +// HTTP body parser
not sure. we should be syncing our master with current master before every push.

For example..
1) Make our changes to our branch
2) Merge brandon:master -> your:master
3) Fix any merge issues on your end and push to your master
4) make PR

2017-11-15 20:42 UTC, bliu23 commented on server/server.js
> +                  `WHERE accepted is NULL`;
To the first question, yeah I think we only want to show nearby unaccepted requests. For the others, that's up to backend :^)

2017-11-15 20:47 UTC, mmxiong commented on server/server.js
> +// HTTP body parser
RIght. But I guess it's unavoidable in this case. Let's try to keep the above as standard procedure in the future.

2017-11-15 21:16 UTC, mmxiong commented on server/server.js
> +                  `WHERE accepted is NULL`;
SGTM

2017-11-16 05:57 UTC, mmxiong requested changes

2017-11-16 05:57 UTC, mmxiong commented on server/server.js
> +                  `AND latitude <= (${latitude} + 5) AND latitude >= (${latitude} - 5) ` +
One degree of latitude is ~69 miles. This looks at a square of 19044 sq miles.

2017-11-16 06:00 UTC, mmxiong approved these changes

2017-11-16 06:00 UTC, mmxiong commented
Approved.

2017-11-16 06:01 UTC, merged