Add distance to user field when getting list of requests. Sort by distance
bliu23/conveni-friends pull request #36
Opened 2017-11-28 08:23 UTC by parkandrew

2017-11-28 08:35 UTC, bliu23 requested changes

2017-11-28 08:35 UTC, bliu23 commented on server/server.js
> +  var R = 6371; // Radius of the earth in km
with Javascript ES6, you can use `let` and `const` keywords instead of `var`.

`let` allows you to declare variables that are limited in scope to the block, statement, or expression on which it is used. This is unlike the `var` keyword, which defines a variable globally, or locally to an entire function regardless of block scope. and `const` is for vars you won't change

2017-11-28 08:35 UTC, bliu23 commented on server/server.js
> +  var R = 6371; // Radius of the earth in km
Also some better variable name would be good

2017-11-28 08:35 UTC, bliu23 commented on server/server.js
> +  var dLat = deg2rad(lat2-lat1);  // deg2rad below
better variable names for dLat, dLon, a, c, d

2017-11-28 08:35 UTC, bliu23 commented on server/server.js
> +function deg2rad(deg) {
degreesToRadians is prob a better function name

2017-11-28 08:35 UTC, bliu23 commented on server/server.js
> +            for (var i = 0; i < results.length; i++) {
let i = 0

2017-11-28 08:35 UTC, bliu23 commented on server/server.js
> +                console.log(results[i]);
can prob remove this line now

2017-11-28 08:35 UTC, bliu23 commented on server/server.js
> +                var dist = getDistanceFromLatLonInMiles(latitude, longitude, results[i].latitude, results[i].longitude);
you can also use let here too.

2017-11-28 08:35 UTC, bliu23 commented on server/server.js
> +            var retValue = [];
`let requestsSortedByDistance = []`
I think when you have to add a comment to describe what a variable name does, it could (usually) just have a better name

2017-11-28 08:37 UTC, bliu23 commented
everything minus javascript specific syntax looks gucci

2017-11-30 00:12 UTC, bliu23 submitted a review, later dismissed

2017-11-30 00:12 UTC, bliu23 commented on server/server.js
> +                return b.distance - a.distance
also iirc if this function is positive, then b is sorted before a. 
so if b.distance = 15 and a.distance = 13, then you get positive, and b comes before a.

2017-12-07 06:11 UTC, jjpestacio commented on server/server.js
> +            retValue.sort(function(a, b) {
ES6 is beautiful: `retValue.sort((a, b) => b.distance - a.distance);`

2017-12-07 06:56 UTC, ArchKevin22 approved these changes

2017-12-07 06:57 UTC, merged