minor changes + more screens to AccountSettings
bliu23/conveni-friends pull request #50
Opened 2017-12-06 05:49 UTC by michelledai

MapScreen -> MapComponent renaming

2017-12-06 05:51 UTC, ArchKevin22 approved these changes

2017-12-06 07:23 UTC, parkandrew requested changes
looks like 44 files were changed and the server/ directory was copied/duplicated into client/server

i have no idea how the front end works, was this supposed to happen?

2017-12-06 07:48 UTC, parkandrew approved these changes

2017-12-07 08:33 UTC, bliu23 commented on client/app/components/CustomButton.js
> +					<Text style={styles.custom_button_font}>{this.props.text}</Text>
wait let's try to keep camel case but it's not a huge deal

2017-12-07 08:33 UTC, bliu23 commented on client/app/screens/LoginScreen.js
> +                onPressHandle={() => {this._signup();}}
i think you can just pass in this._signup but it's not a big deal?

2017-12-07 08:33 UTC, bliu23 commented on client/app/screens/Settings/AccountScreen.js
> +  changepass(){
more camel case stuff but not a big deal. generally styling isn't a huge issue but when projects do grow it's pretty important to just follow the guidelines since someone might call changePass() and wonder why it's not working

2017-12-07 08:33 UTC, bliu23 commented on client/app/screens/Settings/ChangePassword.js
> +            Alert.alert("Invalid/blank username. Please use alphanumeric characters");
Password not username

2017-12-07 08:33 UTC, bliu23 commented on client/app/screens/Settings/ChangePassword.js
> +    _changePass() {
If this is the same function as the username check in login we should probably just use it

2017-12-07 17:11 UTC, merged